openapi: "3.0.0"
info:
  version: 1.0.0
  title: CornettCalc
  license:
    name: Brady R. Cornett
servers:
  - url: http://calculatorbrady-env-1.m2bhvtue83.us-west-2.elasticbeanstalk.com
paths:
  /:
    get:
      summary: Welcome page for web service
      responses:
       '200':
          description: Returns Welcome message
          content:
            application/json:
              schema: 
                type: string
  /calculator:
    get:
      summary: Calculator for web service
      parameters:
        - name: op
          in: query
          description: Operator variable
          required: true
          schema:
            type: string
        - name: fn
          in: query
          description: Variable one
          required: true
          schema:
            type: integer
            format: int32
        - name: ln
          in: query
          description: Variable two
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: Returns array of strings containing variables and 
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
