openapi: 3.0.0
info:
  title: fizzy_counting
  description: The classic FizzBuzz toy function, but as an example of a simple microservice
  version: 0.0.0
servers:
  - url: https://gnis2begf9.execute-api.us-west-2.amazonaws.com/default/fizzy_counting
    description: production endpoint
paths:
  /fizzy_counting:
    get:
      parameters:
        - in: query
          name: max
          schema:
            type: integer
          description: The maximum number you would like the program to count to
        - in: query
          name: rule
          schema:
            type: integer
          description: The parameter name must be an integer, and the value is the string that will be appended if the current value is divisible by the parameter name. Any number of these rules may be submitted
      responses:
        200:
          description: "the fizzy_counting output for a valid set of parameters"
          content: {}
components: {}