branch-defaults:
  default:
    environment: P6a-env
environment-defaults:
  P6a-env:
    branch: null
    repository: null
global:
  application_name: p6a
  default_ec2_keyname: null
  default_platform: arn:aws:elasticbeanstalk:us-east-2::platform/Python 3.6 running
    on 64bit Amazon Linux/2.8.2
  default_region: us-east-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: null
  workspace_type: Application
